export interface LocalFood {
  id: string;
  name: string;
  per100g: {
    calories: number;
    protein: number;
    carbs: number;
    fat: number;
    fiber?: number;
    sugar?: number;
    sodium?: number;
  };
}

export const PT_FOODS: LocalFood[] = [

  // ── FRANGO E AVES (cru e cozinhado) ─────────────────────────────────────────
  { id: "frango_peito_cru",            name: "Frango peito (cru)",                  per100g: { calories: 120, protein: 22, carbs: 0,    fat: 3.0 } },
  { id: "frango_peito_grelhado",       name: "Frango peito (grelhado)",             per100g: { calories: 165, protein: 31, carbs: 0,    fat: 3.6 } },
  { id: "frango_peito_cozido",         name: "Frango peito (cozido)",               per100g: { calories: 150, protein: 30, carbs: 0,    fat: 2.7 } },
  { id: "frango_peito_assado",         name: "Frango peito (assado)",               per100g: { calories: 155, protein: 30, carbs: 0,    fat: 3.0 } },
  { id: "frango_coxa_crua",            name: "Frango coxa (crua)",                  per100g: { calories: 177, protein: 18, carbs: 0,    fat: 11.0 } },
  { id: "frango_coxa_grelhada",        name: "Frango coxa (grelhada)",              per100g: { calories: 220, protein: 26, carbs: 0,    fat: 12.0 } },
  { id: "frango_coxa_cozida",          name: "Frango coxa (cozida)",                per100g: { calories: 197, protein: 24, carbs: 0,    fat: 10.5 } },
  { id: "frango_coxa_assada",          name: "Frango coxa (assada)",                per100g: { calories: 215, protein: 25, carbs: 0,    fat: 12.5 } },
  { id: "frango_asa_crua",             name: "Frango asa (crua)",                   per100g: { calories: 222, protein: 19, carbs: 0,    fat: 16.0 } },
  { id: "frango_inteiro_assado",       name: "Frango inteiro (assado)",             per100g: { calories: 215, protein: 27, carbs: 0,    fat: 12.0 } },
  { id: "frango_picado",               name: "Frango picado (cru)",                 per100g: { calories: 114, protein: 21, carbs: 0.3,  fat: 3.5 } },
  { id: "peru_peito_cru",              name: "Peru peito (cru)",                    per100g: { calories: 104, protein: 23, carbs: 0,    fat: 1.0 } },
  { id: "peru_peito_grelhado",         name: "Peru peito (grelhado)",               per100g: { calories: 135, protein: 29, carbs: 0,    fat: 1.7 } },
  { id: "peru_perna_crua",             name: "Peru perna (crua)",                   per100g: { calories: 142, protein: 20, carbs: 0,    fat: 7.0 } },
  { id: "pato_peito_cru",              name: "Pato peito (cru)",                    per100g: { calories: 133, protein: 19, carbs: 0,    fat: 6.0 } },
  { id: "pato_assado",                 name: "Pato (assado)",                       per100g: { calories: 337, protein: 19, carbs: 0,    fat: 29.0 } },

  // ── BOVINO (cru e cozinhado) ─────────────────────────────────────────────────
  { id: "vaca_bife_cru",               name: "Vaca bife magro (cru)",               per100g: { calories: 143, protein: 21, carbs: 0,    fat: 7.0 } },
  { id: "vaca_bife_grelhado",          name: "Vaca bife (grelhado)",                per100g: { calories: 215, protein: 30, carbs: 0,    fat: 10.5 } },
  { id: "vaca_lombo_cru",              name: "Vaca lombo (cru)",                    per100g: { calories: 192, protein: 20, carbs: 0,    fat: 12.0 } },
  { id: "vaca_alcatra_crua",           name: "Vaca alcatra (crua)",                 per100g: { calories: 120, protein: 21, carbs: 0,    fat: 4.0 } },
  { id: "vaca_alcatra_grelhada",       name: "Vaca alcatra (grelhada)",             per100g: { calories: 160, protein: 28, carbs: 0,    fat: 5.5 } },
  { id: "vaca_vazia_crua",             name: "Vaca vazia (crua)",                   per100g: { calories: 165, protein: 20, carbs: 0,    fat: 9.0 } },
  { id: "vaca_acem_cru",               name: "Vaca acém (cru)",                     per100g: { calories: 172, protein: 19, carbs: 0,    fat: 10.0 } },
  { id: "vaca_pa_crua",                name: "Vaca pá (crua)",                      per100g: { calories: 140, protein: 20, carbs: 0,    fat: 6.5 } },
  { id: "vaca_picada_10",              name: "Vaca picada 10% gordura (crua)",       per100g: { calories: 197, protein: 21, carbs: 0,    fat: 12.7 } },
  { id: "vaca_picada_5",               name: "Vaca picada 5% gordura (crua)",        per100g: { calories: 168, protein: 22, carbs: 0,    fat: 8.5 } },
  { id: "vaca_picada_grelhada",        name: "Vaca picada (grelhada)",              per100g: { calories: 218, protein: 26, carbs: 0,    fat: 12.0 } },
  { id: "vaca_rosbife",                name: "Vaca rosbife (cozido)",               per100g: { calories: 160, protein: 28, carbs: 0,    fat: 5.0 } },
  { id: "vaca_cozida",                 name: "Vaca (cozida)",                       per100g: { calories: 249, protein: 30, carbs: 0,    fat: 14.0 } },
  { id: "vitela_crua",                 name: "Vitela (crua)",                       per100g: { calories: 115, protein: 22, carbs: 0,    fat: 3.0 } },
  { id: "vitela_grelhada",             name: "Vitela (grelhada)",                   per100g: { calories: 151, protein: 30, carbs: 0,    fat: 3.5 } },
  { id: "hamburger_vaca_100g",         name: "Hambúrguer de vaca (100g, cru)",       per100g: { calories: 197, protein: 21, carbs: 0,    fat: 12.7 } },
  { id: "hamburger_vaca_grelhado",     name: "Hambúrguer de vaca (grelhado)",        per100g: { calories: 218, protein: 26, carbs: 0,    fat: 12.0 } },

  // ── SUÍNO (cru e cozinhado) ──────────────────────────────────────────────────
  { id: "porco_lombo_cru",             name: "Porco lombo (cru)",                   per100g: { calories: 143, protein: 22, carbs: 0,    fat: 6.0 } },
  { id: "porco_lombo_grelhado",        name: "Porco lombo (grelhado)",              per100g: { calories: 166, protein: 30, carbs: 0,    fat: 4.7 } },
  { id: "porco_lombinho_cru",          name: "Porco lombinho (cru)",                per100g: { calories: 109, protein: 20, carbs: 0,    fat: 3.0 } },
  { id: "porco_lombinho_grelhado",     name: "Porco lombinho (grelhado)",           per100g: { calories: 143, protein: 27, carbs: 0,    fat: 3.5 } },
  { id: "porco_costeleta_crua",        name: "Porco costeleta (crua)",              per100g: { calories: 240, protein: 19, carbs: 0,    fat: 18.0 } },
  { id: "porco_costeleta_grelhada",    name: "Porco costeleta (grelhada)",          per100g: { calories: 262, protein: 24, carbs: 0,    fat: 18.5 } },
  { id: "porco_entrecosto_cru",        name: "Porco entrecosto (cru)",              per100g: { calories: 269, protein: 20, carbs: 0,    fat: 21.0 } },
  { id: "porco_entrecosto_grelhado",   name: "Porco entrecosto (grelhado)",         per100g: { calories: 283, protein: 25, carbs: 0,    fat: 20.0 } },
  { id: "porco_pa_crua",               name: "Porco pá (crua)",                     per100g: { calories: 215, protein: 18, carbs: 0,    fat: 15.5 } },
  { id: "porco_barriga_crua",          name: "Porco barriga (crua)",                per100g: { calories: 518, protein: 9,  carbs: 0,    fat: 53.0 } },
  { id: "porco_picado_cru",            name: "Porco picado (cru)",                  per100g: { calories: 263, protein: 16, carbs: 0,    fat: 22.0 } },

  // ── CORDEIRO / CABRITO ───────────────────────────────────────────────────────
  { id: "cordeiro_cru",                name: "Cordeiro (cru)",                      per100g: { calories: 282, protein: 17, carbs: 0,    fat: 23.0 } },
  { id: "cordeiro_grelhado",           name: "Cordeiro (grelhado)",                 per100g: { calories: 294, protein: 24, carbs: 0,    fat: 21.0 } },
  { id: "cabrito_cru",                 name: "Cabrito (cru)",                       per100g: { calories: 109, protein: 21, carbs: 0,    fat: 2.5 } },
  { id: "cabrito_assado",              name: "Cabrito (assado)",                    per100g: { calories: 143, protein: 27, carbs: 0,    fat: 3.5 } },

  // ── ENCHIDOS E CARNES FRIAS ──────────────────────────────────────────────────
  { id: "fiambre_peru",                name: "Fiambre de peru",                     per100g: { calories: 109, protein: 17, carbs: 2.0,  fat: 3.5,  sodium: 1000 } },
  { id: "fiambre_porco",               name: "Fiambre de porco",                    per100g: { calories: 122, protein: 16, carbs: 3.0,  fat: 5.0,  sodium: 1100 } },
  { id: "fiambre_peru_equilibrio",     name: "Fiambre Peru Equilibrio (Continente)", per100g: { calories: 99,  protein: 18, carbs: 1.0,  fat: 2.5,  sodium: 900 } },
  { id: "presunto",                    name: "Presunto",                            per100g: { calories: 252, protein: 25, carbs: 0,    fat: 16.0, sodium: 2500 } },
  { id: "presunto_pata_negra",         name: "Presunto pata negra",                 per100g: { calories: 375, protein: 30, carbs: 0,    fat: 28.0, sodium: 1800 } },
  { id: "chourico",                    name: "Chouriço",                            per100g: { calories: 455, protein: 24, carbs: 2.0,  fat: 40.0, sodium: 2200 } },
  { id: "linguica",                    name: "Linguiça",                            per100g: { calories: 408, protein: 18, carbs: 3.0,  fat: 37.0, sodium: 1800 } },
  { id: "paio",                        name: "Paio",                                per100g: { calories: 420, protein: 20, carbs: 2.0,  fat: 37.0, sodium: 1900 } },
  { id: "alheira",                     name: "Alheira",                             per100g: { calories: 369, protein: 15, carbs: 25.0, fat: 24.0 } },
  { id: "morcela",                     name: "Morcela",                             per100g: { calories: 361, protein: 15, carbs: 14.0, fat: 28.0 } },
  { id: "bacon",                       name: "Bacon",                               per100g: { calories: 458, protein: 12, carbs: 1.5,  fat: 45.0, sodium: 1700 } },
  { id: "bacon_grelhado",              name: "Bacon (grelhado)",                    per100g: { calories: 541, protein: 37, carbs: 1.5,  fat: 42.0, sodium: 2400 } },
  { id: "salsicha_frankfurt",          name: "Salsicha Frankfurt",                  per100g: { calories: 301, protein: 12, carbs: 2.0,  fat: 27.0, sodium: 1100 } },
  { id: "salsicha_frango",             name: "Salsicha de frango",                  per100g: { calories: 195, protein: 14, carbs: 3.0,  fat: 15.0, sodium: 900 } },
  { id: "mortadela",                   name: "Mortadela",                           per100g: { calories: 290, protein: 15, carbs: 2.0,  fat: 25.0, sodium: 1300 } },

  // ── BACALHAU ─────────────────────────────────────────────────────────────────
  { id: "bacalhau_salgado_seco",       name: "Bacalhau salgado seco",               per100g: { calories: 322, protein: 76, carbs: 0,    fat: 2.3,  sodium: 8000 } },
  { id: "bacalhau_demolhado_cru",      name: "Bacalhau demolhado (cru)",            per100g: { calories: 76,  protein: 17, carbs: 0,    fat: 0.5,  sodium: 300 } },
  { id: "bacalhau_cozido",             name: "Bacalhau (cozido)",                   per100g: { calories: 105, protein: 24, carbs: 0,    fat: 0.8,  sodium: 300 } },
  { id: "bacalhau_grelhado",           name: "Bacalhau (grelhado)",                 per100g: { calories: 118, protein: 27, carbs: 0,    fat: 0.9 } },
  { id: "bacalhau_assado",             name: "Bacalhau (assado)",                   per100g: { calories: 120, protein: 26, carbs: 0,    fat: 1.5 } },

  // ── SALMÃO ───────────────────────────────────────────────────────────────────
  { id: "salmao_cru",                  name: "Salmão (cru)",                        per100g: { calories: 208, protein: 20, carbs: 0,    fat: 13.4 } },
  { id: "salmao_grelhado",             name: "Salmão (grelhado)",                   per100g: { calories: 182, protein: 25, carbs: 0,    fat: 9.0 } },
  { id: "salmao_cozido",               name: "Salmão (cozido)",                     per100g: { calories: 175, protein: 24, carbs: 0,    fat: 8.5 } },
  { id: "salmao_assado",               name: "Salmão (assado/forno)",               per100g: { calories: 195, protein: 26, carbs: 0,    fat: 10.0 } },
  { id: "salmao_fumado",               name: "Salmão fumado",                       per100g: { calories: 172, protein: 25, carbs: 0,    fat: 8.0,  sodium: 2000 } },

  // ── ATUM ─────────────────────────────────────────────────────────────────────
  { id: "atum_fresco_cru",             name: "Atum fresco (cru)",                   per100g: { calories: 132, protein: 28, carbs: 0,    fat: 1.3 } },
  { id: "atum_fresco_grelhado",        name: "Atum fresco (grelhado)",              per100g: { calories: 184, protein: 30, carbs: 0,    fat: 6.0 } },
  { id: "atum_lata_agua",              name: "Atum em lata (água)",                 per100g: { calories: 116, protein: 25, carbs: 0,    fat: 0.8,  sodium: 330 } },
  { id: "atum_lata_oleo",              name: "Atum em lata (óleo)",                 per100g: { calories: 189, protein: 25, carbs: 0,    fat: 10.0, sodium: 400 } },
  { id: "atum_lata_pingo_doce",        name: "Atum em lata Pingo Doce (água)",       per100g: { calories: 112, protein: 25, carbs: 0,    fat: 0.7,  sodium: 320 } },
  { id: "atum_lata_continente",        name: "Atum em lata Continente (água)",       per100g: { calories: 110, protein: 24, carbs: 0,    fat: 1.0,  sodium: 320 } },

  // ── SARDINHA ─────────────────────────────────────────────────────────────────
  { id: "sardinha_fresca_crua",        name: "Sardinha fresca (crua)",              per100g: { calories: 208, protein: 24, carbs: 0,    fat: 11.5 } },
  { id: "sardinha_assada",             name: "Sardinha (assada/grelhada)",          per100g: { calories: 220, protein: 25, carbs: 0,    fat: 13.0 } },
  { id: "sardinha_lata_oleo",          name: "Sardinha em lata (óleo)",             per100g: { calories: 208, protein: 22, carbs: 0,    fat: 13.0, sodium: 450 } },
  { id: "sardinha_lata_tomate",        name: "Sardinha em lata (tomate)",           per100g: { calories: 150, protein: 17, carbs: 4.0,  fat: 8.0,  sodium: 400 } },
  { id: "sardinha_lata_agua",          name: "Sardinha em lata (água)",             per100g: { calories: 140, protein: 21, carbs: 0,    fat: 6.0,  sodium: 380 } },

  // ── OUTROS PEIXES ────────────────────────────────────────────────────────────
  { id: "dourada_crua",                name: "Dourada (crua)",                      per100g: { calories: 96,  protein: 19, carbs: 0,    fat: 2.0 } },
  { id: "dourada_grelhada",            name: "Dourada (grelhada)",                  per100g: { calories: 115, protein: 22, carbs: 0,    fat: 3.0 } },
  { id: "robalo_cru",                  name: "Robalo (cru)",                        per100g: { calories: 97,  protein: 18, carbs: 0,    fat: 2.5 } },
  { id: "robalo_grelhado",             name: "Robalo (grelhado)",                   per100g: { calories: 110, protein: 22, carbs: 0,    fat: 2.8 } },
  { id: "pescada_crua",                name: "Pescada (crua)",                      per100g: { calories: 72,  protein: 16, carbs: 0,    fat: 0.5 } },
  { id: "pescada_cozida",              name: "Pescada (cozida)",                    per100g: { calories: 90,  protein: 20, carbs: 0,    fat: 0.8 } },
  { id: "pescada_grelhada",            name: "Pescada (grelhada)",                  per100g: { calories: 95,  protein: 21, carbs: 0,    fat: 1.0 } },
  { id: "cavala_crua",                 name: "Cavala (crua)",                       per100g: { calories: 205, protein: 19, carbs: 0,    fat: 13.9 } },
  { id: "cavala_grelhada",             name: "Cavala (grelhada)",                   per100g: { calories: 185, protein: 22, carbs: 0,    fat: 11.0 } },
  { id: "carapau_cru",                 name: "Carapau (cru)",                       per100g: { calories: 112, protein: 20, carbs: 0,    fat: 3.5 } },
  { id: "carapau_grelhado",            name: "Carapau (grelhado)",                  per100g: { calories: 128, protein: 23, carbs: 0,    fat: 4.0 } },
  { id: "linguado_cru",                name: "Linguado (cru)",                      per100g: { calories: 79,  protein: 17, carbs: 0,    fat: 0.5 } },
  { id: "pargo_cru",                   name: "Pargo (cru)",                         per100g: { calories: 100, protein: 21, carbs: 0,    fat: 1.5 } },
  { id: "pargo_grelhado",              name: "Pargo (grelhado)",                    per100g: { calories: 118, protein: 25, carbs: 0,    fat: 2.0 } },
  { id: "pregado_cru",                 name: "Pregado (cru)",                       per100g: { calories: 86,  protein: 17, carbs: 0,    fat: 2.0 } },
  { id: "solha_crua",                  name: "Solha (crua)",                        per100g: { calories: 91,  protein: 18, carbs: 0,    fat: 1.7 } },
  { id: "espadarte_cru",               name: "Espadarte (cru)",                     per100g: { calories: 121, protein: 20, carbs: 0,    fat: 4.4 } },
  { id: "peixe_espada_cru",            name: "Peixe espada preto (cru)",            per100g: { calories: 90,  protein: 19, carbs: 0,    fat: 1.5 } },
  { id: "peixe_espada_grelhado",       name: "Peixe espada preto (grelhado)",       per100g: { calories: 115, protein: 23, carbs: 0,    fat: 2.5 } },
  { id: "ruivo_cru",                   name: "Ruivo (cru)",                         per100g: { calories: 88,  protein: 18, carbs: 0,    fat: 1.8 } },
  { id: "tainha_crua",                 name: "Tainha (crua)",                       per100g: { calories: 117, protein: 19, carbs: 0,    fat: 4.5 } },
  { id: "truta_crua",                  name: "Truta (crua)",                        per100g: { calories: 119, protein: 20, carbs: 0,    fat: 4.3 } },
  { id: "truta_grelhada",              name: "Truta (grelhada)",                    per100g: { calories: 140, protein: 24, carbs: 0,    fat: 5.0 } },
  { id: "enguia_crua",                 name: "Enguia (crua)",                       per100g: { calories: 184, protein: 18, carbs: 0,    fat: 12.0 } },
  { id: "arenque_cru",                 name: "Arenque (cru)",                       per100g: { calories: 158, protein: 18, carbs: 0,    fat: 9.0 } },
  { id: "anchova_cru",                 name: "Anchova / Biqueirão (cru)",           per100g: { calories: 131, protein: 20, carbs: 0,    fat: 5.8 } },

  // ── MARISCOS ─────────────────────────────────────────────────────────────────
  { id: "camarao_cru",                 name: "Camarão (cru)",                       per100g: { calories: 85,  protein: 19, carbs: 0,    fat: 0.5 } },
  { id: "camarao_cozido",              name: "Camarão (cozido)",                    per100g: { calories: 99,  protein: 21, carbs: 0,    fat: 1.3 } },
  { id: "gambas_cruas",                name: "Gambas (cruas)",                      per100g: { calories: 80,  protein: 18, carbs: 0,    fat: 0.5 } },
  { id: "gambas_grelhadas",            name: "Gambas (grelhadas)",                  per100g: { calories: 105, protein: 22, carbs: 0,    fat: 1.5 } },
  { id: "polvo_cru",                   name: "Polvo (cru)",                         per100g: { calories: 82,  protein: 15, carbs: 2.0,  fat: 1.0 } },
  { id: "polvo_cozido",                name: "Polvo (cozido)",                      per100g: { calories: 82,  protein: 15, carbs: 2.2,  fat: 1.0 } },
  { id: "polvo_grelhado",              name: "Polvo (grelhado/lagareiro)",          per100g: { calories: 100, protein: 17, carbs: 2.0,  fat: 2.5 } },
  { id: "lulas_cruas",                 name: "Lulas (cruas)",                       per100g: { calories: 92,  protein: 18, carbs: 3.0,  fat: 1.4 } },
  { id: "lulas_grelhadas",             name: "Lulas (grelhadas)",                   per100g: { calories: 108, protein: 21, carbs: 3.0,  fat: 1.8 } },
  { id: "ameijaos_cruas",              name: "Amêijoas (cruas)",                    per100g: { calories: 74,  protein: 13, carbs: 2.6,  fat: 1.0 } },
  { id: "ameijaos_cozidas",            name: "Amêijoas (cozidas)",                  per100g: { calories: 110, protein: 19, carbs: 3.0,  fat: 1.8 } },
  { id: "mexilhao_cru",                name: "Mexilhão (cru)",                      per100g: { calories: 86,  protein: 12, carbs: 3.7,  fat: 2.2 } },
  { id: "mexilhao_cozido",             name: "Mexilhão (cozido)",                   per100g: { calories: 172, protein: 24, carbs: 7.4,  fat: 4.5 } },
  { id: "berbigao_cru",                name: "Berbigão (cru)",                      per100g: { calories: 50,  protein: 9,  carbs: 2.0,  fat: 0.5 } },
  { id: "lagostim_cru",                name: "Lagostim (cru)",                      per100g: { calories: 72,  protein: 16, carbs: 0,    fat: 0.3 } },
  { id: "sapateira_crua",              name: "Sapateira (crua)",                    per100g: { calories: 89,  protein: 18, carbs: 0,    fat: 1.5 } },
  { id: "vieiras_cruas",               name: "Vieiras (cruas)",                     per100g: { calories: 88,  protein: 17, carbs: 3.2,  fat: 0.8 } },
  { id: "ostra_crua",                  name: "Ostra (crua)",                        per100g: { calories: 68,  protein: 7,  carbs: 4.5,  fat: 2.5 } },
  { id: "pata_roxa_crua",              name: "Pata-roxa / Gamba rosa (crua)",       per100g: { calories: 82,  protein: 18, carbs: 0,    fat: 0.6 } },

  // ── OVOS ─────────────────────────────────────────────────────────────────────
  { id: "ovo_inteiro_cru",             name: "Ovo inteiro (cru)",                   per100g: { calories: 155, protein: 13, carbs: 1.1,  fat: 11.0 } },
  { id: "ovo_cozido",                  name: "Ovo cozido",                          per100g: { calories: 155, protein: 13, carbs: 1.1,  fat: 11.0 } },
  { id: "ovo_mexido",                  name: "Ovo mexido (com leite)",              per100g: { calories: 148, protein: 10, carbs: 1.5,  fat: 11.5 } },
  { id: "ovo_escalfado",               name: "Ovo escalfado",                       per100g: { calories: 143, protein: 12, carbs: 0.7,  fat: 10.0 } },
  { id: "clara_ovo",                   name: "Clara de ovo",                        per100g: { calories: 52,  protein: 11, carbs: 0.7,  fat: 0.2 } },
  { id: "gema_ovo",                    name: "Gema de ovo",                         per100g: { calories: 322, protein: 16, carbs: 1.8,  fat: 27.0 } },

  // ── LACTICÍNIOS ──────────────────────────────────────────────────────────────
  { id: "leite_gordo",                 name: "Leite gordo",                         per100g: { calories: 61,  protein: 3.2, carbs: 4.8, fat: 3.3 } },
  { id: "leite_meio_gordo",            name: "Leite meio gordo",                    per100g: { calories: 46,  protein: 3.2, carbs: 4.8, fat: 1.6 } },
  { id: "leite_magro",                 name: "Leite magro",                         per100g: { calories: 34,  protein: 3.4, carbs: 4.8, fat: 0.1 } },
  { id: "iogurte_natural",             name: "Iogurte natural",                     per100g: { calories: 61,  protein: 3.8, carbs: 4.9, fat: 3.3 } },
  { id: "iogurte_grego_gordo",         name: "Iogurte grego gordo",                 per100g: { calories: 97,  protein: 9.0, carbs: 3.6, fat: 5.0 } },
  { id: "iogurte_grego_0",             name: "Iogurte grego 0% gordura",            per100g: { calories: 57,  protein: 10,  carbs: 3.6, fat: 0.4 } },
  { id: "skyr_0",                      name: "Skyr 0% (tipo Arla/Valio)",           per100g: { calories: 67,  protein: 11,  carbs: 5.0, fat: 0.2 } },
  { id: "iogurte_proteico_ehrmann",    name: "Iogurte proteico Ehrmann High Protein", per100g: { calories: 87, protein: 15, carbs: 5.5, fat: 0.8 } },
  { id: "iogurte_activia_natural",     name: "Iogurte Activia Natural",             per100g: { calories: 70,  protein: 3.8, carbs: 8.4, fat: 2.3 } },
  { id: "iogurte_activia_0",           name: "Iogurte Activia 0%",                  per100g: { calories: 44,  protein: 4.5, carbs: 5.7, fat: 0.1 } },
  { id: "iogurte_equilibrio_0",        name: "Iogurte Equilibrio 0% (Continente)",  per100g: { calories: 44,  protein: 4.0, carbs: 6.0, fat: 0.1 } },
  { id: "queijo_flamengo",             name: "Queijo flamengo",                     per100g: { calories: 313, protein: 23, carbs: 1.6,  fat: 24.0 } },
  { id: "queijo_flamengo_light",       name: "Queijo flamengo light",               per100g: { calories: 220, protein: 27, carbs: 1.5,  fat: 12.0 } },
  { id: "queijo_fresco",               name: "Queijo fresco",                       per100g: { calories: 84,  protein: 9.5, carbs: 3.3, fat: 3.3 } },
  { id: "queijo_fresco_light",         name: "Queijo fresco light",                 per100g: { calories: 60,  protein: 10,  carbs: 3.0, fat: 1.0 } },
  { id: "queijo_babybel",              name: "Queijo Babybel Original",             per100g: { calories: 306, protein: 21, carbs: 0.5,  fat: 25.0 } },
  { id: "queijo_babybel_light",        name: "Queijo Babybel Light",                per100g: { calories: 214, protein: 25, carbs: 0.5,  fat: 13.0 } },
  { id: "queijo_philadelphia",         name: "Queijo Philadelphia Original",        per100g: { calories: 256, protein: 5.5, carbs: 4.1, fat: 25.0 } },
  { id: "queijo_philadelphia_light",   name: "Queijo Philadelphia Light",           per100g: { calories: 143, protein: 6.5, carbs: 3.9, fat: 12.5 } },
  { id: "queijo_cheddar",              name: "Queijo Cheddar",                      per100g: { calories: 403, protein: 25, carbs: 1.3,  fat: 33.0 } },
  { id: "queijo_edam",                 name: "Queijo Edam",                         per100g: { calories: 357, protein: 25, carbs: 1.4,  fat: 28.0 } },
  { id: "queijo_mozzarella",           name: "Mozzarella",                          per100g: { calories: 280, protein: 28, carbs: 3.1,  fat: 17.0 } },
  { id: "queijo_mozzarella_light",     name: "Mozzarella light",                    per100g: { calories: 175, protein: 22, carbs: 3.0,  fat: 9.0 } },
  { id: "queijo_parmesao",             name: "Queijo parmesão",                     per100g: { calories: 431, protein: 38, carbs: 3.2,  fat: 29.0 } },
  { id: "queijo_quark",                name: "Queijo Quark 0%",                     per100g: { calories: 57,  protein: 10, carbs: 4.0,  fat: 0.2 } },
  { id: "queijo_quark_milbona",        name: "Queijo Quark Milbona (Lidl)",         per100g: { calories: 58,  protein: 11, carbs: 4.0,  fat: 0.2 } },
  { id: "queijo_cottage",              name: "Queijo Cottage",                      per100g: { calories: 98,  protein: 11, carbs: 3.4,  fat: 4.3 } },
  { id: "queijo_ricotta",              name: "Ricotta",                             per100g: { calories: 174, protein: 11, carbs: 3.0,  fat: 13.0 } },
  { id: "queijo_creme_light",          name: "Queijo creme light",                  per100g: { calories: 150, protein: 6,  carbs: 4.5,  fat: 11.0 } },
  { id: "requeijao",                   name: "Requeijão",                           per100g: { calories: 168, protein: 10, carbs: 4.3,  fat: 12.3 } },
  { id: "queijo_serra_estrela",        name: "Queijo Serra da Estrela",             per100g: { calories: 350, protein: 22, carbs: 0.5,  fat: 29.0 } },
  { id: "manteiga",                    name: "Manteiga",                            per100g: { calories: 717, protein: 0.9, carbs: 0.1, fat: 81.0 } },
  { id: "manteiga_light",              name: "Manteiga light",                      per100g: { calories: 360, protein: 0.5, carbs: 0.5, fat: 40.0 } },
  { id: "natas_35",                    name: "Natas (35% gordura)",                 per100g: { calories: 345, protein: 2.2, carbs: 3.0, fat: 35.0 } },
  { id: "natas_18",                    name: "Natas (18% gordura)",                 per100g: { calories: 195, protein: 2.7, carbs: 3.5, fat: 19.3 } },

  // ── CEREAIS E PÃO ────────────────────────────────────────────────────────────
  { id: "arroz_branco_cru",            name: "Arroz branco (cru)",                  per100g: { calories: 365, protein: 6.7,  carbs: 80,  fat: 0.7,  fiber: 0.4 } },
  { id: "arroz_branco_cozido",         name: "Arroz branco (cozido)",               per100g: { calories: 130, protein: 2.7,  carbs: 28,  fat: 0.3 } },
  { id: "arroz_integral_cru",          name: "Arroz integral (cru)",                per100g: { calories: 370, protein: 7.9,  carbs: 77,  fat: 2.9,  fiber: 3.5 } },
  { id: "arroz_integral_cozido",       name: "Arroz integral (cozido)",             per100g: { calories: 122, protein: 2.6,  carbs: 25.8, fat: 1.0, fiber: 1.8 } },
  { id: "arroz_basmati_cru",           name: "Arroz basmati (cru)",                 per100g: { calories: 360, protein: 7.5,  carbs: 78,  fat: 0.9,  fiber: 1.0 } },
  { id: "arroz_basmati_cozido",        name: "Arroz basmati (cozido)",              per100g: { calories: 131, protein: 2.7,  carbs: 28.6, fat: 0.3 } },
  { id: "massa_spaghetti_crua",        name: "Massa esparguete (crua)",             per100g: { calories: 371, protein: 13.4, carbs: 74,  fat: 1.5,  fiber: 3.2 } },
  { id: "massa_spaghetti_cozida",      name: "Massa esparguete (cozida)",           per100g: { calories: 157, protein: 5.8,  carbs: 31,  fat: 0.9 } },
  { id: "massa_penne_crua",            name: "Massa penne (crua)",                  per100g: { calories: 371, protein: 13,   carbs: 74,  fat: 1.5,  fiber: 3.0 } },
  { id: "massa_penne_cozida",          name: "Massa penne (cozida)",                per100g: { calories: 157, protein: 5.8,  carbs: 31,  fat: 0.9 } },
  { id: "massa_integral_crua",         name: "Massa integral (crua)",               per100g: { calories: 348, protein: 13.4, carbs: 68,  fat: 2.5,  fiber: 8.0 } },
  { id: "massa_integral_cozida",       name: "Massa integral (cozida)",             per100g: { calories: 124, protein: 5.3,  carbs: 23,  fat: 1.0,  fiber: 3.5 } },
  { id: "aveia",                       name: "Aveia (flocos)",                      per100g: { calories: 379, protein: 13,   carbs: 67,  fat: 7.0,  fiber: 10.0 } },
  { id: "aveia_quaker",                name: "Aveia Quaker",                        per100g: { calories: 379, protein: 13.5, carbs: 66,  fat: 7.3,  fiber: 10.0 } },
  { id: "pao_branco",                  name: "Pão branco",                          per100g: { calories: 265, protein: 8.5,  carbs: 49,  fat: 3.2,  fiber: 2.7 } },
  { id: "pao_integral",                name: "Pão integral",                        per100g: { calories: 247, protein: 9.0,  carbs: 41,  fat: 3.4,  fiber: 7.0 } },
  { id: "pao_forma_branco",            name: "Pão de forma branco",                 per100g: { calories: 264, protein: 8.0,  carbs: 50,  fat: 3.3 } },
  { id: "pao_forma_integral",          name: "Pão de forma integral",               per100g: { calories: 240, protein: 9.0,  carbs: 42,  fat: 3.5,  fiber: 7.0 } },
  { id: "pao_centeio",                 name: "Pão de centeio",                      per100g: { calories: 258, protein: 8.5,  carbs: 48,  fat: 3.3,  fiber: 6.0 } },
  { id: "pao_alentejano",              name: "Pão alentejano",                      per100g: { calories: 262, protein: 9.0,  carbs: 50,  fat: 2.5 } },
  { id: "baguete",                     name: "Baguete / cacete",                    per100g: { calories: 270, protein: 9.0,  carbs: 51,  fat: 3.0 } },
  { id: "wrap_tortilha",               name: "Wrap / Tortilha de trigo",            per100g: { calories: 295, protein: 7.0,  carbs: 53,  fat: 6.5 } },
  { id: "tostas_integrais",            name: "Tostas integrais",                    per100g: { calories: 380, protein: 11,   carbs: 68,  fat: 6.0,  fiber: 8.0 } },
  { id: "bolachas_maria",              name: "Bolachas Maria",                      per100g: { calories: 415, protein: 7.0,  carbs: 74,  fat: 10.5 } },
  { id: "bolachas_aveia",              name: "Bolachas de aveia",                   per100g: { calories: 430, protein: 8.0,  carbs: 65,  fat: 17.0, fiber: 5.0 } },
  { id: "batata_crua",                 name: "Batata (crua)",                       per100g: { calories: 77,  protein: 2.0,  carbs: 17,  fat: 0.1,  fiber: 2.2 } },
  { id: "batata_cozida",               name: "Batata (cozida)",                     per100g: { calories: 87,  protein: 1.9,  carbs: 20,  fat: 0.1,  fiber: 1.8 } },
  { id: "batata_assada",               name: "Batata (assada)",                     per100g: { calories: 93,  protein: 2.5,  carbs: 21,  fat: 0.1 } },
  { id: "batata_frita_caseira",        name: "Batata frita (caseira)",              per100g: { calories: 312, protein: 3.4,  carbs: 36,  fat: 17.5 } },
  { id: "batata_frita_fast_food",      name: "Batata frita (fast food)",            per100g: { calories: 312, protein: 3.4,  carbs: 40,  fat: 15.5 } },
  { id: "batata_doce_crua",            name: "Batata doce (crua)",                  per100g: { calories: 86,  protein: 1.6,  carbs: 20,  fat: 0.1,  fiber: 3.0 } },
  { id: "batata_doce_cozida",          name: "Batata doce (cozida)",                per100g: { calories: 76,  protein: 1.4,  carbs: 18,  fat: 0.1,  fiber: 2.5 } },
  { id: "quinoa_crua",                 name: "Quinoa (crua)",                       per100g: { calories: 368, protein: 14,   carbs: 64,  fat: 6.1,  fiber: 7.0 } },
  { id: "quinoa_cozida",               name: "Quinoa (cozida)",                     per100g: { calories: 120, protein: 4.4,  carbs: 21.3, fat: 1.9, fiber: 2.8 } },
  { id: "cuscus_seco",                 name: "Cuscus (seco)",                       per100g: { calories: 376, protein: 13,   carbs: 77,  fat: 0.6 } },
  { id: "cuscus_cozido",               name: "Cuscus (cozido)",                     per100g: { calories: 112, protein: 3.8,  carbs: 23,  fat: 0.2 } },
  { id: "cornflakes",                  name: "Cornflakes / Cereais de milho",       per100g: { calories: 362, protein: 7.5,  carbs: 84,  fat: 0.9,  fiber: 3.0 } },
  { id: "muesli",                      name: "Muesli",                              per100g: { calories: 360, protein: 10,   carbs: 64,  fat: 6.0,  fiber: 8.0 } },
  { id: "granola",                     name: "Granola",                             per100g: { calories: 471, protein: 9.4,  carbs: 64,  fat: 20.0, fiber: 7.0 } },
  { id: "weetabix",                    name: "Weetabix",                            per100g: { calories: 362, protein: 11.5, carbs: 70,  fat: 2.0,  fiber: 10.0 } },
  { id: "special_k",                   name: "Special K",                           per100g: { calories: 379, protein: 16,   carbs: 73,  fat: 2.0 } },
  { id: "all_bran",                    name: "All Bran",                            per100g: { calories: 334, protein: 14,   carbs: 48,  fat: 4.0,  fiber: 27.0 } },

  // ── LEGUMINOSAS ──────────────────────────────────────────────────────────────
  { id: "feijao_vermelho_cozido",      name: "Feijão vermelho (cozido)",            per100g: { calories: 127, protein: 8.7,  carbs: 23,  fat: 0.5,  fiber: 6.4 } },
  { id: "feijao_branco_cozido",        name: "Feijão branco (cozido)",              per100g: { calories: 139, protein: 9.7,  carbs: 25,  fat: 0.4,  fiber: 6.0 } },
  { id: "feijao_preto_cozido",         name: "Feijão preto (cozido)",               per100g: { calories: 132, protein: 8.9,  carbs: 24,  fat: 0.5,  fiber: 8.7 } },
  { id: "feijao_frade_cozido",         name: "Feijão frade (cozido)",               per100g: { calories: 116, protein: 8.0,  carbs: 21,  fat: 0.5,  fiber: 6.5 } },
  { id: "grao_cozido",                 name: "Grão de bico (cozido)",               per100g: { calories: 164, protein: 8.9,  carbs: 27,  fat: 2.6,  fiber: 7.6 } },
  { id: "lentilhas_cozidas",           name: "Lentilhas (cozidas)",                 per100g: { calories: 116, protein: 9.0,  carbs: 20,  fat: 0.4,  fiber: 7.9 } },
  { id: "ervilhas",                    name: "Ervilhas",                            per100g: { calories: 81,  protein: 5.4,  carbs: 14,  fat: 0.4,  fiber: 5.1 } },
  { id: "soja_cozida",                 name: "Soja (cozida)",                       per100g: { calories: 173, protein: 16.6, carbs: 9.9, fat: 9.0,  fiber: 6.0 } },
  { id: "tofu",                        name: "Tofu",                                per100g: { calories: 76,  protein: 8.0,  carbs: 1.9, fat: 4.8 } },
  { id: "tofu_fumado",                 name: "Tofu fumado",                         per100g: { calories: 120, protein: 14,   carbs: 2.0, fat: 6.5 } },
  { id: "tempeh",                      name: "Tempeh",                              per100g: { calories: 192, protein: 20,   carbs: 7.6, fat: 11.0, fiber: 5.0 } },
  { id: "hummus",                      name: "Hummus",                              per100g: { calories: 166, protein: 7.9,  carbs: 14,  fat: 9.6,  fiber: 6.0 } },

  // ── VEGETAIS ─────────────────────────────────────────────────────────────────
  { id: "brocoulos",                   name: "Brócolos",                            per100g: { calories: 34,  protein: 2.8,  carbs: 7.0, fat: 0.4,  fiber: 2.6 } },
  { id: "espinafres",                  name: "Espinafres",                          per100g: { calories: 23,  protein: 2.9,  carbs: 3.6, fat: 0.4,  fiber: 2.2 } },
  { id: "tomate",                      name: "Tomate",                              per100g: { calories: 18,  protein: 0.9,  carbs: 3.9, fat: 0.2,  fiber: 1.2 } },
  { id: "tomate_cherry",               name: "Tomate cherry",                       per100g: { calories: 18,  protein: 0.9,  carbs: 3.9, fat: 0.2 } },
  { id: "cebola",                      name: "Cebola",                              per100g: { calories: 40,  protein: 1.1,  carbs: 9.3, fat: 0.1,  fiber: 1.7 } },
  { id: "cebola_roxa",                 name: "Cebola roxa",                         per100g: { calories: 40,  protein: 1.1,  carbs: 9.3, fat: 0.1 } },
  { id: "alho",                        name: "Alho",                                per100g: { calories: 149, protein: 6.4,  carbs: 33,  fat: 0.5 } },
  { id: "cenoura",                     name: "Cenoura",                             per100g: { calories: 41,  protein: 0.9,  carbs: 9.6, fat: 0.2,  fiber: 2.8 } },
  { id: "alface",                      name: "Alface",                              per100g: { calories: 15,  protein: 1.4,  carbs: 2.9, fat: 0.2,  fiber: 1.3 } },
  { id: "pepino",                      name: "Pepino",                              per100g: { calories: 15,  protein: 0.7,  carbs: 3.6, fat: 0.1 } },
  { id: "courgette",                   name: "Courgette",                           per100g: { calories: 17,  protein: 1.2,  carbs: 3.1, fat: 0.3,  fiber: 1.0 } },
  { id: "feijao_verde",                name: "Feijão verde",                        per100g: { calories: 31,  protein: 1.8,  carbs: 7.0, fat: 0.1,  fiber: 3.4 } },
  { id: "cogumelos",                   name: "Cogumelos",                           per100g: { calories: 22,  protein: 3.1,  carbs: 3.3, fat: 0.3,  fiber: 1.0 } },
  { id: "pimento_vermelho",            name: "Pimento vermelho",                    per100g: { calories: 31,  protein: 1.0,  carbs: 6.0, fat: 0.3,  fiber: 2.1 } },
  { id: "pimento_verde",               name: "Pimento verde",                       per100g: { calories: 20,  protein: 0.9,  carbs: 4.6, fat: 0.2 } },
  { id: "pimento_amarelo",             name: "Pimento amarelo",                     per100g: { calories: 27,  protein: 1.0,  carbs: 6.3, fat: 0.2 } },
  { id: "beringela",                   name: "Beringela",                           per100g: { calories: 25,  protein: 1.0,  carbs: 5.9, fat: 0.2,  fiber: 3.0 } },
  { id: "couve_flor",                  name: "Couve-flor",                          per100g: { calories: 25,  protein: 1.9,  carbs: 5.0, fat: 0.3,  fiber: 2.0 } },
  { id: "couve_lombarda",              name: "Couve lombarda",                      per100g: { calories: 27,  protein: 1.8,  carbs: 6.0, fat: 0.1,  fiber: 2.5 } },
  { id: "couve_galega",                name: "Couve galega",                        per100g: { calories: 36,  protein: 3.3,  carbs: 7.0, fat: 0.7,  fiber: 3.6 } },
  { id: "couve_portuguesa",            name: "Couve portuguesa",                    per100g: { calories: 29,  protein: 2.0,  carbs: 5.5, fat: 0.3,  fiber: 2.8 } },
  { id: "kale",                        name: "Kale / Couve kale",                   per100g: { calories: 49,  protein: 4.3,  carbs: 9.0, fat: 0.9,  fiber: 3.6 } },
  { id: "espargos",                    name: "Espargos",                            per100g: { calories: 20,  protein: 2.2,  carbs: 3.9, fat: 0.1,  fiber: 2.1 } },
  { id: "beterraba",                   name: "Beterraba",                           per100g: { calories: 43,  protein: 1.6,  carbs: 10,  fat: 0.2,  fiber: 2.8 } },
  { id: "milho_cozido",                name: "Milho (cozido)",                      per100g: { calories: 96,  protein: 3.4,  carbs: 21,  fat: 1.5,  fiber: 2.4 } },
  { id: "milho_lata",                  name: "Milho em lata",                       per100g: { calories: 86,  protein: 3.0,  carbs: 19,  fat: 1.2,  fiber: 2.0 } },
  { id: "alho_porro",                  name: "Alho-porro",                          per100g: { calories: 61,  protein: 1.5,  carbs: 14,  fat: 0.3 } },
  { id: "aipo",                        name: "Aipo",                                per100g: { calories: 16,  protein: 0.7,  carbs: 3.0, fat: 0.2 } },
  { id: "abobora",                     name: "Abóbora",                             per100g: { calories: 26,  protein: 1.0,  carbs: 6.5, fat: 0.1 } },
  { id: "nabo",                        name: "Nabo",                                per100g: { calories: 28,  protein: 0.9,  carbs: 6.4, fat: 0.1 } },
  { id: "rucula",                      name: "Rúcula",                              per100g: { calories: 25,  protein: 2.6,  carbs: 3.7, fat: 0.7 } },
  { id: "rabanete",                    name: "Rabanete",                            per100g: { calories: 16,  protein: 0.7,  carbs: 3.4, fat: 0.1 } },
  { id: "agriao",                      name: "Agrião",                              per100g: { calories: 11,  protein: 2.3,  carbs: 1.3, fat: 0.1 } },

  // ── FRUTAS ───────────────────────────────────────────────────────────────────
  { id: "banana",                      name: "Banana",                              per100g: { calories: 89,  protein: 1.1,  carbs: 23,  fat: 0.3,  fiber: 2.6 } },
  { id: "maca",                        name: "Maçã",                                per100g: { calories: 52,  protein: 0.3,  carbs: 14,  fat: 0.2,  fiber: 2.4 } },
  { id: "laranja",                     name: "Laranja",                             per100g: { calories: 47,  protein: 0.9,  carbs: 12,  fat: 0.1,  fiber: 2.4 } },
  { id: "morango",                     name: "Morango",                             per100g: { calories: 32,  protein: 0.7,  carbs: 7.7, fat: 0.3,  fiber: 2.0 } },
  { id: "uva",                         name: "Uva",                                 per100g: { calories: 69,  protein: 0.7,  carbs: 18,  fat: 0.2,  fiber: 0.9 } },
  { id: "pera",                        name: "Pêra",                                per100g: { calories: 57,  protein: 0.4,  carbs: 15,  fat: 0.1,  fiber: 3.1 } },
  { id: "pessego",                     name: "Pêssego",                             per100g: { calories: 39,  protein: 0.9,  carbs: 10,  fat: 0.3,  fiber: 1.5 } },
  { id: "melancia",                    name: "Melancia",                            per100g: { calories: 30,  protein: 0.6,  carbs: 7.6, fat: 0.2 } },
  { id: "melao",                       name: "Melão",                               per100g: { calories: 34,  protein: 0.8,  carbs: 8.2, fat: 0.2 } },
  { id: "abacate",                     name: "Abacate",                             per100g: { calories: 160, protein: 2.0,  carbs: 9.0, fat: 15.0, fiber: 6.7 } },
  { id: "framboesa",                   name: "Framboesa",                           per100g: { calories: 52,  protein: 1.2,  carbs: 12,  fat: 0.7,  fiber: 6.5 } },
  { id: "mirtilo",                     name: "Mirtilo",                             per100g: { calories: 57,  protein: 0.7,  carbs: 14,  fat: 0.3,  fiber: 2.4 } },
  { id: "manga",                       name: "Manga",                               per100g: { calories: 60,  protein: 0.8,  carbs: 15,  fat: 0.4,  fiber: 1.6 } },
  { id: "ananas",                      name: "Ananás",                              per100g: { calories: 50,  protein: 0.5,  carbs: 13,  fat: 0.1,  fiber: 1.4 } },
  { id: "kiwi",                        name: "Kiwi",                                per100g: { calories: 61,  protein: 1.1,  carbs: 15,  fat: 0.5,  fiber: 3.0 } },
  { id: "cereja",                      name: "Cereja",                              per100g: { calories: 63,  protein: 1.1,  carbs: 16,  fat: 0.2 } },
  { id: "damasco",                     name: "Damasco",                             per100g: { calories: 48,  protein: 1.4,  carbs: 11,  fat: 0.4,  fiber: 2.0 } },
  { id: "lima",                        name: "Lima",                                per100g: { calories: 30,  protein: 0.7,  carbs: 10,  fat: 0.2 } },
  { id: "limao",                       name: "Limão",                               per100g: { calories: 29,  protein: 1.1,  carbs: 9.3, fat: 0.3 } },
  { id: "roma",                        name: "Romã",                                per100g: { calories: 83,  protein: 1.7,  carbs: 19,  fat: 1.2,  fiber: 4.0 } },
  { id: "figo",                        name: "Figo",                                per100g: { calories: 74,  protein: 0.8,  carbs: 19,  fat: 0.3 } },
  { id: "tamara_seca",                 name: "Tâmara (seca)",                       per100g: { calories: 282, protein: 2.5,  carbs: 75,  fat: 0.4,  fiber: 8.0 } },
  { id: "papaia",                      name: "Papaia",                              per100g: { calories: 43,  protein: 0.5,  carbs: 11,  fat: 0.3,  fiber: 1.7 } },
  { id: "tangerina",                   name: "Tangerina / Clementina",              per100g: { calories: 53,  protein: 0.8,  carbs: 13,  fat: 0.3 } },
  { id: "coco_fresco",                 name: "Coco (fresco)",                       per100g: { calories: 354, protein: 3.3,  carbs: 15,  fat: 33.5, fiber: 9.0 } },

  // ── GORDURAS, ÓLEOS E FRUTOS SECOS ──────────────────────────────────────────
  { id: "azeite",                      name: "Azeite",                              per100g: { calories: 884, protein: 0,    carbs: 0,   fat: 100.0 } },
  { id: "oleo_girassol",               name: "Óleo de girassol",                    per100g: { calories: 884, protein: 0,    carbs: 0,   fat: 100.0 } },
  { id: "oleo_coco",                   name: "Óleo de coco",                        per100g: { calories: 892, protein: 0,    carbs: 0,   fat: 99.0 } },
  { id: "manteiga_amendoim",           name: "Manteiga de amendoim",                per100g: { calories: 588, protein: 25,   carbs: 20,  fat: 50.0, fiber: 6.0 } },
  { id: "manteiga_amendoa",            name: "Manteiga de amêndoa",                 per100g: { calories: 614, protein: 21,   carbs: 19,  fat: 56.0, fiber: 12.0 } },
  { id: "amendoim",                    name: "Amendoim",                            per100g: { calories: 567, protein: 25.8, carbs: 16,  fat: 49.2, fiber: 8.5 } },
  { id: "amendoa",                     name: "Amêndoa",                             per100g: { calories: 579, protein: 21,   carbs: 22,  fat: 50.0, fiber: 12.5 } },
  { id: "noz",                         name: "Noz",                                 per100g: { calories: 654, protein: 15,   carbs: 14,  fat: 65.0, fiber: 6.7 } },
  { id: "caju",                        name: "Caju",                                per100g: { calories: 553, protein: 18,   carbs: 30,  fat: 44.0, fiber: 3.3 } },
  { id: "avela",                       name: "Avelã",                               per100g: { calories: 628, protein: 15,   carbs: 17,  fat: 61.0, fiber: 9.7 } },
  { id: "pistache",                    name: "Pistachio",                           per100g: { calories: 560, protein: 20,   carbs: 28,  fat: 45.0, fiber: 10.0 } },
  { id: "sementes_abobora",            name: "Sementes de abóbora",                 per100g: { calories: 559, protein: 30,   carbs: 11,  fat: 49.0, fiber: 6.0 } },
  { id: "sementes_chia",               name: "Sementes de chia",                    per100g: { calories: 486, protein: 17,   carbs: 42,  fat: 31.0, fiber: 34.0 } },
  { id: "sementes_linhaça",            name: "Sementes de linhaça",                 per100g: { calories: 534, protein: 18,   carbs: 29,  fat: 42.0, fiber: 27.0 } },
  { id: "sementes_girassol",           name: "Sementes de girassol",                per100g: { calories: 584, protein: 21,   carbs: 20,  fat: 51.0, fiber: 8.6 } },
  { id: "tahini",                      name: "Tahini (pasta sésamo)",               per100g: { calories: 595, protein: 17,   carbs: 21,  fat: 54.0, fiber: 9.0 } },

  // ── SUPLEMENTOS ──────────────────────────────────────────────────────────────
  { id: "whey_proteina",               name: "Whey proteína em pó",                 per100g: { calories: 400, protein: 80,   carbs: 10,  fat: 6.7 } },
  { id: "caseina_proteina",            name: "Caseína em pó",                       per100g: { calories: 370, protein: 80,   carbs: 8.0, fat: 2.0 } },
  { id: "proteina_vegana",             name: "Proteína vegana em pó",               per100g: { calories: 380, protein: 75,   carbs: 12,  fat: 6.0 } },
  { id: "creatina",                    name: "Creatina monohidratada",               per100g: { calories: 0,   protein: 0,    carbs: 0,   fat: 0 } },
  { id: "bcaa_em_po",                  name: "BCAA em pó",                          per100g: { calories: 120, protein: 30,   carbs: 0,   fat: 0 } },

  // ── BEBIDAS ──────────────────────────────────────────────────────────────────
  { id: "leite_aveia",                 name: "Leite de aveia",                      per100g: { calories: 47,  protein: 1.0,  carbs: 7.9, fat: 1.5 } },
  { id: "leite_amendoa_sem_acucar",    name: "Leite de amêndoa sem açúcar",         per100g: { calories: 13,  protein: 0.5,  carbs: 0.8, fat: 0.7 } },
  { id: "leite_soja",                  name: "Leite de soja",                       per100g: { calories: 33,  protein: 2.9,  carbs: 1.6, fat: 1.9 } },
  { id: "leite_coco",                  name: "Leite de coco",                       per100g: { calories: 230, protein: 2.3,  carbs: 5.5, fat: 24.0 } },
  { id: "alpro_soja_natural",          name: "Alpro Soja Natural",                  per100g: { calories: 40,  protein: 3.3,  carbs: 2.5, fat: 1.9 } },
  { id: "alpro_aveia",                 name: "Alpro Aveia",                         per100g: { calories: 45,  protein: 1.0,  carbs: 6.6, fat: 1.5 } },
  { id: "sumo_laranja",                name: "Sumo de laranja natural",             per100g: { calories: 45,  protein: 0.7,  carbs: 10.4, fat: 0.2 } },
  { id: "agua_coco",                   name: "Água de coco",                        per100g: { calories: 19,  protein: 0.7,  carbs: 3.7, fat: 0.2 } },

  // ── CONDIMENTOS E MOLHOS ─────────────────────────────────────────────────────
  { id: "azeite_colher",               name: "Azeite (1 colher = 14ml)",            per100g: { calories: 884, protein: 0,    carbs: 0,   fat: 100.0 } },
  { id: "ketchup",                     name: "Ketchup",                             per100g: { calories: 112, protein: 1.3,  carbs: 27,  fat: 0.1,  sodium: 900 } },
  { id: "molho_soja",                  name: "Molho de soja",                       per100g: { calories: 53,  protein: 8.0,  carbs: 5.0, fat: 0.1,  sodium: 5700 } },
  { id: "molho_soja_light",            name: "Molho de soja light (menos sal)",     per100g: { calories: 40,  protein: 6.0,  carbs: 4.0, fat: 0.1,  sodium: 3200 } },
  { id: "maionese",                    name: "Maionese",                            per100g: { calories: 680, protein: 1.0,  carbs: 0.6, fat: 75.0 } },
  { id: "maionese_light",              name: "Maionese light",                      per100g: { calories: 215, protein: 1.0,  carbs: 10,  fat: 19.0 } },
  { id: "mostarda",                    name: "Mostarda",                            per100g: { calories: 60,  protein: 4.4,  carbs: 5.8, fat: 3.3 } },
  { id: "vinagre",                     name: "Vinagre",                             per100g: { calories: 18,  protein: 0,    carbs: 0.9, fat: 0 } },
  { id: "mel",                         name: "Mel",                                 per100g: { calories: 304, protein: 0.3,  carbs: 82,  fat: 0,    sugar: 82 } },
  { id: "acucar_branco",               name: "Açúcar branco",                       per100g: { calories: 387, protein: 0,    carbs: 100, fat: 0,    sugar: 100 } },
  { id: "acucar_mascavado",            name: "Açúcar mascavado",                    per100g: { calories: 380, protein: 0,    carbs: 98,  fat: 0 } },
  { id: "compota",                     name: "Compota / Geleia",                    per100g: { calories: 250, protein: 0.3,  carbs: 65,  fat: 0 } },

  // ── SNACKS E DOCES ───────────────────────────────────────────────────────────
  { id: "chocolate_negro_85",          name: "Chocolate negro 85%",                 per100g: { calories: 598, protein: 12,   carbs: 21,  fat: 52.0, fiber: 12.0 } },
  { id: "chocolate_negro_70",          name: "Chocolate negro 70%",                 per100g: { calories: 566, protein: 10,   carbs: 33,  fat: 43.0 } },
  { id: "chocolate_leite",             name: "Chocolate de leite",                  per100g: { calories: 535, protein: 7.6,  carbs: 59,  fat: 30.0 } },
  { id: "pastel_nata",                 name: "Pastel de nata",                      per100g: { calories: 280, protein: 6.0,  carbs: 36,  fat: 13.0 } },
  { id: "pastel_feijao",               name: "Pastel de feijão",                    per100g: { calories: 290, protein: 5.0,  carbs: 50,  fat: 9.0 } },
  { id: "arroz_doce",                  name: "Arroz doce",                          per100g: { calories: 133, protein: 3.5,  carbs: 26,  fat: 2.5 } },
  { id: "bola_de_berlim",              name: "Bola de Berlim",                      per100g: { calories: 305, protein: 5.0,  carbs: 45,  fat: 13.0 } },
  { id: "croissant_simples",           name: "Croissant simples",                   per100g: { calories: 406, protein: 8.2,  carbs: 46,  fat: 22.0 } },

  // ── PRATOS PORTUGUESES TÍPICOS (por 100g preparado) ─────────────────────────
  { id: "caldo_verde",                 name: "Caldo verde",                         per100g: { calories: 48,  protein: 1.8,  carbs: 7.0, fat: 1.5 } },
  { id: "sopa_legumes",                name: "Sopa de legumes caseira",             per100g: { calories: 35,  protein: 1.5,  carbs: 7.0, fat: 0.5 } },
  { id: "arroz_tomate",                name: "Arroz de tomate",                     per100g: { calories: 128, protein: 2.8,  carbs: 27,  fat: 1.0 } },
  { id: "arroz_frango",                name: "Arroz de frango",                     per100g: { calories: 145, protein: 10,   carbs: 18,  fat: 3.5 } },
  { id: "arroz_bacalhau",              name: "Arroz de bacalhau",                   per100g: { calories: 130, protein: 9.0,  carbs: 19,  fat: 2.0 } },
  { id: "bacalhau_bras",               name: "Bacalhau à Brás",                     per100g: { calories: 210, protein: 14,   carbs: 18,  fat: 9.0 } },
  { id: "bacalhau_lagareiro",          name: "Bacalhau à Lagareiro",                per100g: { calories: 185, protein: 18,   carbs: 2.0, fat: 12.0 } },
  { id: "frango_piri_piri",            name: "Frango piri-piri (assado)",           per100g: { calories: 198, protein: 25,   carbs: 2.0, fat: 10.0 } },
  { id: "cozido_portugues",            name: "Cozido à portuguesa",                 per100g: { calories: 188, protein: 14,   carbs: 12,  fat: 10.0 } },
  { id: "bifana",                      name: "Bifana (só carne)",                   per100g: { calories: 215, protein: 24,   carbs: 2.0, fat: 13.0 } },
  { id: "prego_no_pao",                name: "Prego no pão",                        per100g: { calories: 200, protein: 14,   carbs: 19,  fat: 7.0 } },
  { id: "feijoada",                    name: "Feijoada",                            per100g: { calories: 160, protein: 10,   carbs: 14,  fat: 7.0 } },

  // ── MASSAS E PREPARADOS ──────────────────────────────────────────────────────
  { id: "lasanha",                     name: "Lasanha (preparada)",                 per100g: { calories: 130, protein: 8.0,  carbs: 12,  fat: 5.5 } },
  { id: "pizza_margherita",            name: "Pizza margherita",                    per100g: { calories: 250, protein: 10,   carbs: 33,  fat: 9.0 } },
  { id: "hamburger_completo",          name: "Hambúrguer completo",                 per100g: { calories: 295, protein: 15,   carbs: 24,  fat: 15.0 } },
  { id: "hot_dog",                     name: "Hot dog (com pão)",                   per100g: { calories: 268, protein: 10,   carbs: 26,  fat: 14.0 } },

];

export function searchLocalFoods(query: string): LocalFood[] {
  if (!query || query.trim().length === 0) return [];
  const words = query
    .toLowerCase()
    .trim()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .split(/\s+/)
    .filter(Boolean);

  const results = PT_FOODS.filter((food) => {
    const normalized = food.name
      .toLowerCase()
      .normalize("NFD")
      .replace(/[̀-ͯ]/g, "");
    return words.every((word) => normalized.includes(word));
  });
  return results.slice(0, 20);
}
