export interface LocalFood {
  id: string;
  name: string;
  per100g: {
    calories: number;
    protein: number;
    carbs: number;
    fat: number;
    fiber?: number;
    sugar?: number;
    sodium?: number;
  };
}

export const PT_FOODS: LocalFood[] = [
  // ── Carnes e Aves ──────────────────────────────────────────────────────────
  { id: "frango_grelhado_peito", name: "Frango grelhado (peito)", per100g: { calories: 165, protein: 31, carbs: 0, fat: 3.6 } },
  { id: "frango_cozido_peito", name: "Frango cozido (peito)", per100g: { calories: 150, protein: 30, carbs: 0, fat: 2.7 } },
  { id: "frango_assado_coxa", name: "Frango assado (coxa)", per100g: { calories: 220, protein: 26, carbs: 0, fat: 12 } },
  { id: "peito_peru", name: "Peito de peru", per100g: { calories: 135, protein: 29, carbs: 0, fat: 1.7 } },
  { id: "vaca_bife_magro", name: "Vaca (bife magro)", per100g: { calories: 143, protein: 26, carbs: 0, fat: 4.3 } },
  { id: "vaca_picada_10", name: "Vaca picada (10% gordura)", per100g: { calories: 197, protein: 21, carbs: 0, fat: 12.7 } },
  { id: "vaca_picada_5", name: "Vaca picada (5% gordura)", per100g: { calories: 168, protein: 22, carbs: 0, fat: 8.5 } },
  { id: "porco_lombo", name: "Porco (lombo)", per100g: { calories: 182, protein: 25, carbs: 0, fat: 8.7 } },
  { id: "porco_entrecosto", name: "Porco (entrecosto)", per100g: { calories: 270, protein: 20, carbs: 0, fat: 21 } },
  { id: "cordeiro", name: "Cordeiro", per100g: { calories: 282, protein: 17, carbs: 0, fat: 23 } },
  { id: "fiambre_peru", name: "Fiambre (peru)", per100g: { calories: 109, protein: 17, carbs: 2, fat: 3.5 } },
  { id: "fiambre_porco", name: "Fiambre (porco)", per100g: { calories: 122, protein: 16, carbs: 3, fat: 5 } },
  { id: "bacon", name: "Bacon", per100g: { calories: 458, protein: 12, carbs: 1.5, fat: 45 } },
  { id: "chourico", name: "Chouriço", per100g: { calories: 455, protein: 24, carbs: 2, fat: 40 } },
  { id: "salsicha", name: "Salsicha", per100g: { calories: 301, protein: 12, carbs: 2, fat: 27 } },
  { id: "frango_inteiro_assado", name: "Frango inteiro assado", per100g: { calories: 239, protein: 27, carbs: 0, fat: 14 } },
  { id: "peru_assado", name: "Peru assado", per100g: { calories: 189, protein: 29, carbs: 0, fat: 7.4 } },
  { id: "pato", name: "Pato", per100g: { calories: 337, protein: 19, carbs: 0, fat: 28 } },
  { id: "coelho", name: "Coelho", per100g: { calories: 173, protein: 33, carbs: 0, fat: 4 } },
  { id: "vitela", name: "Vitela", per100g: { calories: 167, protein: 26, carbs: 0, fat: 6.4 } },
  { id: "presunto", name: "Presunto", per100g: { calories: 270, protein: 26, carbs: 0, fat: 18 } },
  { id: "morcela", name: "Morcela", per100g: { calories: 379, protein: 14, carbs: 8, fat: 33 } },

  // ── Peixe e Marisco ────────────────────────────────────────────────────────
  { id: "salmao_cru", name: "Salmão (cru)", per100g: { calories: 208, protein: 20, carbs: 0, fat: 13.4 } },
  { id: "salmao_cozido", name: "Salmão (cozido)", per100g: { calories: 182, protein: 25, carbs: 0, fat: 9 } },
  { id: "atum_fresco", name: "Atum (fresco)", per100g: { calories: 132, protein: 28, carbs: 0, fat: 1.3 } },
  { id: "atum_lata_agua", name: "Atum em lata (água)", per100g: { calories: 116, protein: 25, carbs: 0, fat: 0.8 } },
  { id: "atum_lata_oleo", name: "Atum em lata (óleo)", per100g: { calories: 189, protein: 25, carbs: 0, fat: 10 } },
  { id: "bacalhau_cozido", name: "Bacalhau (demolhado cozido)", per100g: { calories: 105, protein: 24, carbs: 0, fat: 0.8, sodium: 300 } },
  { id: "sardinha_fresca", name: "Sardinha (fresca)", per100g: { calories: 208, protein: 24, carbs: 0, fat: 11.5 } },
  { id: "sardinha_lata", name: "Sardinha (lata óleo)", per100g: { calories: 208, protein: 22, carbs: 0, fat: 13 } },
  { id: "cavala", name: "Cavala", per100g: { calories: 205, protein: 19, carbs: 0, fat: 13.9 } },
  { id: "dourada", name: "Dourada", per100g: { calories: 96, protein: 19, carbs: 0, fat: 2 } },
  { id: "robalo", name: "Robalo", per100g: { calories: 97, protein: 18, carbs: 0, fat: 2.5 } },
  { id: "camarao_cozido", name: "Camarão cozido", per100g: { calories: 99, protein: 21, carbs: 0, fat: 1.3 } },
  { id: "polvo_cozido", name: "Polvo cozido", per100g: { calories: 82, protein: 15, carbs: 2.2, fat: 1 } },
  { id: "lulas", name: "Lulas", per100g: { calories: 92, protein: 18, carbs: 3, fat: 1.4 } },
  { id: "ameijoas", name: "Amêijoas", per100g: { calories: 74, protein: 13, carbs: 2.6, fat: 1 } },
  { id: "linguado", name: "Linguado", per100g: { calories: 91, protein: 19, carbs: 0, fat: 1.4 } },
  { id: "pescada", name: "Pescada", per100g: { calories: 86, protein: 17.8, carbs: 0, fat: 1.4 } },
  { id: "truta", name: "Truta", per100g: { calories: 141, protein: 20, carbs: 0, fat: 6.6 } },
  { id: "mexilhao", name: "Mexilhão", per100g: { calories: 86, protein: 12, carbs: 3.7, fat: 2.2 } },
  { id: "lagostim", name: "Lagostim", per100g: { calories: 90, protein: 19, carbs: 0, fat: 1 } },
  { id: "caranguejo", name: "Caranguejo", per100g: { calories: 97, protein: 19, carbs: 0, fat: 2 } },

  // ── Ovos e Laticínios ──────────────────────────────────────────────────────
  { id: "ovo_inteiro", name: "Ovo inteiro", per100g: { calories: 155, protein: 13, carbs: 1.1, fat: 11 } },
  { id: "clara_ovo", name: "Clara de ovo", per100g: { calories: 52, protein: 11, carbs: 0.7, fat: 0.2 } },
  { id: "gema_ovo", name: "Gema de ovo", per100g: { calories: 322, protein: 16, carbs: 3.6, fat: 27 } },
  { id: "leite_gordo", name: "Leite gordo", per100g: { calories: 61, protein: 3.2, carbs: 4.8, fat: 3.3 } },
  { id: "leite_meio_gordo", name: "Leite meio gordo", per100g: { calories: 46, protein: 3.2, carbs: 4.8, fat: 1.6 } },
  { id: "leite_magro", name: "Leite magro", per100g: { calories: 34, protein: 3.4, carbs: 4.8, fat: 0.1 } },
  { id: "iogurte_natural", name: "Iogurte natural", per100g: { calories: 61, protein: 3.8, carbs: 4.9, fat: 3.3 } },
  { id: "iogurte_grego_0", name: "Iogurte grego (0%)", per100g: { calories: 57, protein: 10, carbs: 3.6, fat: 0.4 } },
  { id: "iogurte_grego_gordo", name: "Iogurte grego (gordo)", per100g: { calories: 97, protein: 9, carbs: 3.6, fat: 5 } },
  { id: "queijo_flamengo", name: "Queijo flamengo", per100g: { calories: 313, protein: 23, carbs: 1.6, fat: 24 } },
  { id: "queijo_fresco", name: "Queijo fresco", per100g: { calories: 84, protein: 9.5, carbs: 3.3, fat: 3.3 } },
  { id: "requeijao", name: "Requeijão", per100g: { calories: 168, protein: 10, carbs: 4.3, fat: 12.3 } },
  { id: "mozzarella", name: "Mozzarella", per100g: { calories: 280, protein: 28, carbs: 3.1, fat: 17 } },
  { id: "queijo_cheddar", name: "Queijo Cheddar", per100g: { calories: 403, protein: 25, carbs: 1.3, fat: 33 } },
  { id: "queijo_edam", name: "Queijo Edam", per100g: { calories: 357, protein: 25, carbs: 1.4, fat: 28 } },
  { id: "ricotta", name: "Ricotta", per100g: { calories: 174, protein: 11, carbs: 3, fat: 13 } },
  { id: "manteiga", name: "Manteiga", per100g: { calories: 717, protein: 0.9, carbs: 0.1, fat: 81 } },
  { id: "natas_35", name: "Natas (35%)", per100g: { calories: 345, protein: 2.2, carbs: 3, fat: 35 } },
  { id: "natas_18", name: "Natas (18%)", per100g: { calories: 195, protein: 2.7, carbs: 3.5, fat: 19.3 } },
  { id: "queijo_parmesao", name: "Queijo parmesão", per100g: { calories: 431, protein: 38, carbs: 3.2, fat: 29 } },
  { id: "cream_cheese", name: "Cream cheese", per100g: { calories: 342, protein: 6, carbs: 4.1, fat: 34 } },

  // ── Cereais, Pão e Massas ──────────────────────────────────────────────────
  { id: "arroz_branco_cru", name: "Arroz branco (cru)", per100g: { calories: 365, protein: 6.7, carbs: 80, fat: 0.7, fiber: 0.4 } },
  { id: "arroz_branco_cozido", name: "Arroz branco (cozido)", per100g: { calories: 130, protein: 2.7, carbs: 28, fat: 0.3 } },
  { id: "arroz_integral_cru", name: "Arroz integral (cru)", per100g: { calories: 370, protein: 7.9, carbs: 77, fat: 2.9, fiber: 3.5 } },
  { id: "arroz_integral_cozido", name: "Arroz integral (cozido)", per100g: { calories: 122, protein: 2.6, carbs: 25.8, fat: 1, fiber: 1.8 } },
  { id: "massa_esparguete_crua", name: "Massa esparguete (crua)", per100g: { calories: 371, protein: 13.4, carbs: 74, fat: 1.5, fiber: 3.2 } },
  { id: "massa_esparguete_cozida", name: "Massa esparguete (cozida)", per100g: { calories: 157, protein: 5.8, carbs: 31, fat: 0.9 } },
  { id: "massa_integral_crua", name: "Massa integral (crua)", per100g: { calories: 348, protein: 13.4, carbs: 68, fat: 2.5, fiber: 8 } },
  { id: "aveia", name: "Aveia", per100g: { calories: 379, protein: 13, carbs: 67, fat: 7, fiber: 10 } },
  { id: "pao_branco", name: "Pão branco", per100g: { calories: 265, protein: 8.5, carbs: 49, fat: 3.2, fiber: 2.7 } },
  { id: "pao_integral", name: "Pão integral", per100g: { calories: 247, protein: 9, carbs: 41, fat: 3.4, fiber: 7 } },
  { id: "pao_forma_branco", name: "Pão de forma branco", per100g: { calories: 264, protein: 8, carbs: 50, fat: 3.3 } },
  { id: "pao_forma_integral", name: "Pão de forma integral", per100g: { calories: 240, protein: 9, carbs: 42, fat: 3.5, fiber: 7 } },
  { id: "batata_cozida", name: "Batata cozida", per100g: { calories: 87, protein: 1.9, carbs: 20, fat: 0.1, fiber: 1.8 } },
  { id: "batata_assada", name: "Batata assada", per100g: { calories: 93, protein: 2.5, carbs: 21, fat: 0.1 } },
  { id: "batata_doce_cozida", name: "Batata doce cozida", per100g: { calories: 86, protein: 1.6, carbs: 20, fat: 0.1, fiber: 3 } },
  { id: "quinoa_cozida", name: "Quinoa cozida", per100g: { calories: 120, protein: 4.4, carbs: 21.3, fat: 1.9, fiber: 2.8 } },
  { id: "cuscus_cozido", name: "Cuscus cozido", per100g: { calories: 112, protein: 3.8, carbs: 23, fat: 0.2 } },
  { id: "cornflakes", name: "Cornflakes", per100g: { calories: 362, protein: 7.5, carbs: 84, fat: 0.9, fiber: 3 } },
  { id: "granola", name: "Granola", per100g: { calories: 471, protein: 9.4, carbs: 64, fat: 20, fiber: 7 } },
  { id: "bolachas_maria", name: "Bolachas Maria", per100g: { calories: 415, protein: 7, carbs: 74, fat: 10.5 } },
  { id: "tostas_integrais", name: "Tostas integrais", per100g: { calories: 380, protein: 11, carbs: 68, fat: 6, fiber: 8 } },
  { id: "wrap_tortilha", name: "Wrap / Tortilha", per100g: { calories: 295, protein: 7, carbs: 53, fat: 6.5 } },
  { id: "batata_frita", name: "Batata frita", per100g: { calories: 312, protein: 3.4, carbs: 41, fat: 15 } },
  { id: "massa_lasanha_cozida", name: "Massa lasanha (cozida)", per100g: { calories: 155, protein: 5.7, carbs: 30, fat: 0.9 } },
  { id: "pao_centeio", name: "Pão de centeio", per100g: { calories: 259, protein: 8.5, carbs: 48, fat: 3.3, fiber: 6.2 } },
  { id: "muesli", name: "Muesli", per100g: { calories: 363, protein: 10, carbs: 66, fat: 6.9, fiber: 7 } },

  // ── Leguminosas ────────────────────────────────────────────────────────────
  { id: "feijao_vermelho_cozido", name: "Feijão vermelho cozido", per100g: { calories: 127, protein: 8.7, carbs: 23, fat: 0.5, fiber: 6.4 } },
  { id: "feijao_branco_cozido", name: "Feijão branco cozido", per100g: { calories: 139, protein: 9.7, carbs: 25, fat: 0.4, fiber: 6 } },
  { id: "feijao_preto_cozido", name: "Feijão preto cozido", per100g: { calories: 132, protein: 8.9, carbs: 24, fat: 0.5, fiber: 8.7 } },
  { id: "grao_bico_cozido", name: "Grão de bico cozido", per100g: { calories: 164, protein: 8.9, carbs: 27, fat: 2.6, fiber: 7.6 } },
  { id: "lentilhas_cozidas", name: "Lentilhas cozidas", per100g: { calories: 116, protein: 9, carbs: 20, fat: 0.4, fiber: 7.9 } },
  { id: "ervilhas", name: "Ervilhas", per100g: { calories: 81, protein: 5.4, carbs: 14, fat: 0.4, fiber: 5.1 } },
  { id: "soja_cozida", name: "Soja cozida", per100g: { calories: 173, protein: 16.6, carbs: 9.9, fat: 9, fiber: 6 } },
  { id: "tofu", name: "Tofu", per100g: { calories: 76, protein: 8, carbs: 1.9, fat: 4.8 } },
  { id: "tempeh", name: "Tempeh", per100g: { calories: 193, protein: 19, carbs: 9, fat: 11 } },
  { id: "edamame", name: "Edamame", per100g: { calories: 121, protein: 11, carbs: 8.9, fat: 5.2, fiber: 5 } },
  { id: "feijao_frade_cozido", name: "Feijão frade cozido", per100g: { calories: 116, protein: 7.7, carbs: 21, fat: 0.5, fiber: 6.5 } },

  // ── Vegetais ───────────────────────────────────────────────────────────────
  { id: "broculos", name: "Brócolos", per100g: { calories: 34, protein: 2.8, carbs: 7, fat: 0.4, fiber: 2.6 } },
  { id: "espinafres", name: "Espinafres", per100g: { calories: 23, protein: 2.9, carbs: 3.6, fat: 0.4, fiber: 2.2 } },
  { id: "tomate", name: "Tomate", per100g: { calories: 18, protein: 0.9, carbs: 3.9, fat: 0.2, fiber: 1.2 } },
  { id: "cebola", name: "Cebola", per100g: { calories: 40, protein: 1.1, carbs: 9.3, fat: 0.1, fiber: 1.7 } },
  { id: "alho", name: "Alho", per100g: { calories: 149, protein: 6.4, carbs: 33, fat: 0.5 } },
  { id: "cenoura", name: "Cenoura", per100g: { calories: 41, protein: 0.9, carbs: 9.6, fat: 0.2, fiber: 2.8 } },
  { id: "alface", name: "Alface", per100g: { calories: 15, protein: 1.4, carbs: 2.9, fat: 0.2, fiber: 1.3 } },
  { id: "pepino", name: "Pepino", per100g: { calories: 15, protein: 0.7, carbs: 3.6, fat: 0.1 } },
  { id: "courgette", name: "Courgette", per100g: { calories: 17, protein: 1.2, carbs: 3.1, fat: 0.3, fiber: 1 } },
  { id: "feijao_verde", name: "Feijão verde", per100g: { calories: 31, protein: 1.8, carbs: 7, fat: 0.1, fiber: 3.4 } },
  { id: "cogumelos", name: "Cogumelos", per100g: { calories: 22, protein: 3.1, carbs: 3.3, fat: 0.3, fiber: 1 } },
  { id: "pimento_vermelho", name: "Pimento vermelho", per100g: { calories: 31, protein: 1, carbs: 6, fat: 0.3, fiber: 2.1 } },
  { id: "pimento_verde", name: "Pimento verde", per100g: { calories: 20, protein: 0.9, carbs: 4.6, fat: 0.2 } },
  { id: "beringela", name: "Beringela", per100g: { calories: 25, protein: 1, carbs: 5.9, fat: 0.2, fiber: 3 } },
  { id: "couve_flor", name: "Couve-flor", per100g: { calories: 25, protein: 1.9, carbs: 5, fat: 0.3, fiber: 2 } },
  { id: "couve_lombarda", name: "Couve lombarda", per100g: { calories: 27, protein: 1.8, carbs: 6, fat: 0.1, fiber: 2.5 } },
  { id: "couve_galega", name: "Couve galega", per100g: { calories: 36, protein: 3.3, carbs: 7, fat: 0.7, fiber: 3.6 } },
  { id: "kale", name: "Kale", per100g: { calories: 49, protein: 4.3, carbs: 9, fat: 0.9, fiber: 3.6 } },
  { id: "espargos", name: "Espargos", per100g: { calories: 20, protein: 2.2, carbs: 3.9, fat: 0.1, fiber: 2.1 } },
  { id: "beterraba", name: "Beterraba", per100g: { calories: 43, protein: 1.6, carbs: 10, fat: 0.2, fiber: 2.8 } },
  { id: "milho_cozido", name: "Milho (grão cozido)", per100g: { calories: 96, protein: 3.4, carbs: 21, fat: 1.5, fiber: 2.4 } },
  { id: "alho_porro", name: "Alho-porro", per100g: { calories: 61, protein: 1.5, carbs: 14, fat: 0.3 } },
  { id: "aipo", name: "Aipo", per100g: { calories: 16, protein: 0.7, carbs: 3, fat: 0.2 } },
  { id: "abobora", name: "Abóbora", per100g: { calories: 26, protein: 1, carbs: 6.5, fat: 0.1 } },
  { id: "nabo", name: "Nabo", per100g: { calories: 28, protein: 0.9, carbs: 6.4, fat: 0.1 } },
  { id: "rucula", name: "Rúcula", per100g: { calories: 25, protein: 2.6, carbs: 3.7, fat: 0.7 } },
  { id: "cebola_roxa", name: "Cebola roxa", per100g: { calories: 40, protein: 1.1, carbs: 9.3, fat: 0.1 } },
  { id: "tomate_cereja", name: "Tomate cereja", per100g: { calories: 18, protein: 0.9, carbs: 3.9, fat: 0.2 } },
  { id: "rabano", name: "Rábano", per100g: { calories: 16, protein: 0.7, carbs: 3.4, fat: 0.1 } },
  { id: "agriao", name: "Agrião", per100g: { calories: 11, protein: 2.3, carbs: 1.3, fat: 0.1 } },

  // ── Frutas ─────────────────────────────────────────────────────────────────
  { id: "banana", name: "Banana", per100g: { calories: 89, protein: 1.1, carbs: 23, fat: 0.3, fiber: 2.6 } },
  { id: "maca", name: "Maçã", per100g: { calories: 52, protein: 0.3, carbs: 14, fat: 0.2, fiber: 2.4 } },
  { id: "laranja", name: "Laranja", per100g: { calories: 47, protein: 0.9, carbs: 12, fat: 0.1, fiber: 2.4 } },
  { id: "morango", name: "Morango", per100g: { calories: 32, protein: 0.7, carbs: 7.7, fat: 0.3, fiber: 2 } },
  { id: "uva", name: "Uva", per100g: { calories: 69, protein: 0.7, carbs: 18, fat: 0.2, fiber: 0.9 } },
  { id: "pera", name: "Pêra", per100g: { calories: 57, protein: 0.4, carbs: 15, fat: 0.1, fiber: 3.1 } },
  { id: "pessego", name: "Pêssego", per100g: { calories: 39, protein: 0.9, carbs: 10, fat: 0.3, fiber: 1.5 } },
  { id: "melancia", name: "Melancia", per100g: { calories: 30, protein: 0.6, carbs: 7.6, fat: 0.2 } },
  { id: "melao", name: "Melão", per100g: { calories: 34, protein: 0.8, carbs: 8.2, fat: 0.2 } },
  { id: "abacate", name: "Abacate", per100g: { calories: 160, protein: 2, carbs: 9, fat: 15, fiber: 6.7 } },
  { id: "framboesa", name: "Framboesa", per100g: { calories: 52, protein: 1.2, carbs: 12, fat: 0.7, fiber: 6.5 } },
  { id: "mirtilo", name: "Mirtilo", per100g: { calories: 57, protein: 0.7, carbs: 14, fat: 0.3, fiber: 2.4 } },
  { id: "manga", name: "Manga", per100g: { calories: 60, protein: 0.8, carbs: 15, fat: 0.4, fiber: 1.6 } },
  { id: "ananas", name: "Ananás", per100g: { calories: 50, protein: 0.5, carbs: 13, fat: 0.1, fiber: 1.4 } },
  { id: "kiwi", name: "Kiwi", per100g: { calories: 61, protein: 1.1, carbs: 15, fat: 0.5, fiber: 3 } },
  { id: "cereja", name: "Cereja", per100g: { calories: 63, protein: 1.1, carbs: 16, fat: 0.2 } },
  { id: "damasco", name: "Damasco", per100g: { calories: 48, protein: 1.4, carbs: 11, fat: 0.4, fiber: 2 } },
  { id: "limao", name: "Limão", per100g: { calories: 29, protein: 1.1, carbs: 9.3, fat: 0.3 } },
  { id: "roma", name: "Romã", per100g: { calories: 83, protein: 1.7, carbs: 19, fat: 1.2, fiber: 4 } },
  { id: "figo", name: "Figo", per100g: { calories: 74, protein: 0.8, carbs: 19, fat: 0.3 } },
  { id: "tamara_seca", name: "Tâmara (seca)", per100g: { calories: 282, protein: 2.5, carbs: 75, fat: 0.4, fiber: 8 } },
  { id: "ameixa", name: "Ameixa", per100g: { calories: 46, protein: 0.7, carbs: 11.4, fat: 0.3 } },
  { id: "papaia", name: "Papaia", per100g: { calories: 43, protein: 0.5, carbs: 11, fat: 0.3, fiber: 1.7 } },
  { id: "coco_ralado", name: "Côco ralado", per100g: { calories: 354, protein: 3.3, carbs: 15, fat: 33, fiber: 9 } },

  // ── Gorduras, Frutos Secos e Sementes ──────────────────────────────────────
  { id: "azeite", name: "Azeite", per100g: { calories: 884, protein: 0, carbs: 0, fat: 100 } },
  { id: "oleo_girassol", name: "Óleo de girassol", per100g: { calories: 884, protein: 0, carbs: 0, fat: 100 } },
  { id: "manteiga_amendoim", name: "Manteiga de amendoim", per100g: { calories: 588, protein: 25, carbs: 20, fat: 50, fiber: 6 } },
  { id: "amendoim", name: "Amendoim", per100g: { calories: 567, protein: 25.8, carbs: 16, fat: 49.2, fiber: 8.5 } },
  { id: "amendoa", name: "Amêndoa", per100g: { calories: 579, protein: 21, carbs: 22, fat: 50, fiber: 12.5 } },
  { id: "noz", name: "Noz", per100g: { calories: 654, protein: 15, carbs: 14, fat: 65, fiber: 6.7 } },
  { id: "caju", name: "Caju", per100g: { calories: 553, protein: 18, carbs: 30, fat: 44, fiber: 3.3 } },
  { id: "avela", name: "Avelã", per100g: { calories: 628, protein: 15, carbs: 17, fat: 61, fiber: 9.7 } },
  { id: "sementes_abobora", name: "Sementes de abóbora", per100g: { calories: 559, protein: 30, carbs: 11, fat: 49, fiber: 6 } },
  { id: "sementes_chia", name: "Sementes de chia", per100g: { calories: 486, protein: 17, carbs: 42, fat: 31, fiber: 34 } },
  { id: "sementes_linhaca", name: "Sementes de linhaça", per100g: { calories: 534, protein: 18, carbs: 29, fat: 42, fiber: 27 } },
  { id: "sementes_girassol", name: "Sementes de girassol", per100g: { calories: 584, protein: 21, carbs: 20, fat: 51, fiber: 8.6 } },
  { id: "tahini", name: "Tahini", per100g: { calories: 595, protein: 17, carbs: 21, fat: 54, fiber: 9 } },
  { id: "pistacio", name: "Pistacho", per100g: { calories: 562, protein: 20, carbs: 28, fat: 45, fiber: 10 } },
  { id: "castanha_para", name: "Castanha do Pará", per100g: { calories: 659, protein: 14, carbs: 12, fat: 67 } },
  { id: "coco_oleo", name: "Óleo de coco", per100g: { calories: 862, protein: 0, carbs: 0, fat: 100 } },
  { id: "castanha", name: "Castanha cozida", per100g: { calories: 131, protein: 2, carbs: 28, fat: 1.1, fiber: 5.1 } },

  // ── Suplementos e Proteínas ────────────────────────────────────────────────
  { id: "whey_protein", name: "Whey protein em pó", per100g: { calories: 400, protein: 80, carbs: 10, fat: 6.7 } },
  { id: "proteina_vegana", name: "Proteína vegana em pó", per100g: { calories: 380, protein: 75, carbs: 12, fat: 6 } },
  { id: "caseina", name: "Caseína em pó", per100g: { calories: 370, protein: 80, carbs: 8, fat: 2 } },
  { id: "creatina", name: "Creatina monohidratada", per100g: { calories: 0, protein: 0, carbs: 0, fat: 0 } },
  { id: "bcaa", name: "BCAA", per100g: { calories: 0, protein: 0, carbs: 0, fat: 0 } },

  // ── Bebidas ────────────────────────────────────────────────────────────────
  { id: "leite_aveia", name: "Leite de aveia", per100g: { calories: 47, protein: 1, carbs: 7.9, fat: 1.5 } },
  { id: "leite_amendoa", name: "Leite de amêndoa sem açúcar", per100g: { calories: 13, protein: 0.5, carbs: 0.8, fat: 0.7 } },
  { id: "leite_soja", name: "Leite de soja", per100g: { calories: 33, protein: 2.9, carbs: 1.6, fat: 1.9 } },
  { id: "leite_coco", name: "Leite de coco", per100g: { calories: 230, protein: 2.3, carbs: 5.5, fat: 24 } },
  { id: "sumo_laranja", name: "Sumo de laranja", per100g: { calories: 45, protein: 0.7, carbs: 10.4, fat: 0.2 } },
  { id: "agua_coco", name: "Água de coco", per100g: { calories: 19, protein: 0.7, carbs: 3.7, fat: 0.2 } },
  { id: "leite_arroz", name: "Leite de arroz", per100g: { calories: 47, protein: 0.3, carbs: 9.2, fat: 1 } },
  { id: "cafe_preto", name: "Café preto", per100g: { calories: 2, protein: 0.3, carbs: 0, fat: 0 } },
  { id: "cha_verde", name: "Chá verde", per100g: { calories: 1, protein: 0.2, carbs: 0.2, fat: 0 } },

  // ── Produtos de Supermercado ────────────────────────────────────────────────
  { id: "atum_pd_agua", name: "Atum Pingo Doce (lata água)", per100g: { calories: 110, protein: 24, carbs: 0, fat: 1, sodium: 320 } },
  { id: "iogurte_proteico_skyr", name: "Iogurte proteico 0% (Skyr)", per100g: { calories: 67, protein: 11, carbs: 5, fat: 0.2 } },
  { id: "queijo_quark", name: "Queijo Quark 0%", per100g: { calories: 57, protein: 10, carbs: 4, fat: 0.2 } },
  { id: "chocolate_negro_85", name: "Chocolate negro 85%", per100g: { calories: 598, protein: 12, carbs: 21, fat: 52, fiber: 12 } },
  { id: "chocolate_negro_70", name: "Chocolate negro 70%", per100g: { calories: 566, protein: 10, carbs: 33, fat: 43 } },
  { id: "mel", name: "Mel", per100g: { calories: 304, protein: 0.3, carbs: 82, fat: 0 } },
  { id: "acucar_branco", name: "Açúcar branco", per100g: { calories: 387, protein: 0, carbs: 100, fat: 0 } },
  { id: "acucar_mascavado", name: "Açúcar mascavado", per100g: { calories: 380, protein: 0, carbs: 98, fat: 0 } },
  { id: "geleia_compota", name: "Geleia / Compota", per100g: { calories: 250, protein: 0.3, carbs: 65, fat: 0 } },
  { id: "ketchup", name: "Ketchup", per100g: { calories: 112, protein: 1.3, carbs: 27, fat: 0.1, sodium: 900 } },
  { id: "molho_soja", name: "Molho de soja", per100g: { calories: 53, protein: 8, carbs: 5, fat: 0.1, sodium: 5700 } },
  { id: "maionese", name: "Maionese", per100g: { calories: 680, protein: 1, carbs: 0.6, fat: 75 } },
  { id: "mostarda", name: "Mostarda", per100g: { calories: 60, protein: 4.4, carbs: 5.8, fat: 3.3 } },
  { id: "hummus", name: "Hummus", per100g: { calories: 166, protein: 7.9, carbs: 14, fat: 9.6, fiber: 6 } },
  { id: "queijo_creme_light", name: "Queijo creme light", per100g: { calories: 150, protein: 6, carbs: 4.5, fat: 11 } },
  { id: "fiambre_light", name: "Fiambre light", per100g: { calories: 90, protein: 14, carbs: 2, fat: 3 } },
  { id: "molho_tomate", name: "Molho de tomate", per100g: { calories: 29, protein: 1.4, carbs: 6.4, fat: 0.2 } },
  { id: "azeite_spray", name: "Azeite spray", per100g: { calories: 884, protein: 0, carbs: 0, fat: 100 } },
  { id: "levedura_nutricional", name: "Levedura nutricional", per100g: { calories: 325, protein: 50, carbs: 38, fat: 5, fiber: 24 } },

  // ── Refeições Prontas e Outros ─────────────────────────────────────────────
  { id: "sopa_legumes", name: "Sopa de legumes caseira", per100g: { calories: 35, protein: 1.5, carbs: 7, fat: 0.5, fiber: 1.5 } },
  { id: "arroz_frango", name: "Arroz de frango", per100g: { calories: 142, protein: 10, carbs: 18, fat: 3.5 } },
  { id: "omelete", name: "Omelete (2 ovos)", per100g: { calories: 154, protein: 11, carbs: 0.5, fat: 12 } },
  { id: "ovos_mexidos", name: "Ovos mexidos", per100g: { calories: 148, protein: 10, carbs: 1, fat: 11 } },
  { id: "pizza_margarita", name: "Pizza margarita", per100g: { calories: 266, protein: 11, carbs: 33, fat: 10 } },
  { id: "hamburguer_caseiro", name: "Hambúrguer caseiro", per100g: { calories: 295, protein: 17, carbs: 24, fat: 13 } },
  { id: "caldo_verde", name: "Caldo verde", per100g: { calories: 47, protein: 1.5, carbs: 7.5, fat: 1.2 } },
  { id: "pao_misto", name: "Pão misto", per100g: { calories: 260, protein: 8.8, carbs: 47, fat: 3.3 } },
  { id: "croissant", name: "Croissant", per100g: { calories: 406, protein: 8.2, carbs: 46, fat: 21 } },
];

export function searchLocalFoods(query: string): LocalFood[] {
  if (!query || query.trim().length === 0) return [];
  const words = query.toLowerCase().trim().split(/\s+/).filter(Boolean);
  const results = PT_FOODS.filter((food) => {
    const nameLower = food.name.toLowerCase();
    return words.every((word) => nameLower.includes(word));
  });
  return results.slice(0, 20);
}
