import type { Lang } from "@/lib/training/base-plan";
import { ebookPrice } from "@/lib/ebook/price";

/**
 * The two things someone can pay for.
 *
 * Until now there was one price, 127 euros, and everyone who could not pay it
 * was simply lost at the end of the trial. The app already writes a real plan
 * from the signup answers and logs every set, which costs nothing per client,
 * so it can be sold on its own. What 127 buys is the coach: a plan he writes
 * from what you logged, adjusted every week.
 *
 * Keeping the cheaper tier honest is the whole point. It must not be sold as
 * coaching, and the app must never imply a person is reading the logs when
 * nobody is.
 */

export type Tier = "app" | "coaching";

export interface TierInfo {
  id: Tier;
  amountCents: number;
  productName: string;
  name: Record<Lang, string>;
  tagline: Record<Lang, string>;
  includes: Record<Lang, string[]>;
  /** Said plainly, so nobody discovers it after paying. */
  excludes?: Record<Lang, string[]>;
}

export const TIERS: Record<Tier, TierInfo> = {
  app: {
    id: "app",
    amountCents: 3500,
    productName: "KRAV App",
    name: { pt: "App", en: "App" },
    tagline: {
      pt: "O método, montado pela app à volta da tua semana.",
      en: "The method, built by the app around your week.",
    },
    includes: {
      pt: [
        "Plano de treino montado a partir das tuas respostas, todas as semanas",
        "Treino guiado com registo de séries, pesos e descanso",
        "Comparação automática com a semana anterior",
        "Histórico, progresso e registo alimentar",
        "AI Coach 24/7 para tirar dúvidas sobre treino e nutrição",
        "Semana mais leve a cada 4 semanas, como manda o método",
        `O livro 90 Dias incluído, que à parte custa €${ebookPrice("pt")}`,
      ],
      en: [
        "A training week built from your answers, every week",
        "Guided sessions with set, weight and rest logging",
        "Automatic comparison with last week",
        "History, progress and food logging",
        "AI Coach 24/7 for training and nutrition questions",
        "A lighter week every 4 weeks, as the method asks",
        `The 90 Days book included, which costs €${ebookPrice("en")} on its own`,
      ],
    },
    excludes: {
      pt: [
        "O plano é gerado pela app, não é escrito pelo André",
        "Sem ajustes semanais feitos por uma pessoa",
      ],
      en: [
        "The plan is generated by the app, not written by André",
        "No weekly adjustments made by a person",
      ],
    },
  },
  coaching: {
    id: "coaching",
    amountCents: 12700,
    productName: "KRAV Premium Coaching",
    name: { pt: "Coaching 1:1", en: "1:1 Coaching" },
    tagline: {
      pt: "O André escreve o teu plano e ajusta-o todas as semanas.",
      en: "André writes your plan and adjusts it every week.",
    },
    includes: {
      pt: [
        "Tudo o que a App inclui",
        "Plano escrito pelo André a partir do que registaste",
        "Ajustes todas as semanas com base na tua evolução real",
        "Exercícios trocados quando algo dói ou o ginásio está cheio",
        "Acompanhamento nutricional adaptado ao teu objetivo",
        "Chat direto com o coach, com resposta no mesmo dia",
      ],
      en: [
        "Everything in App",
        "A plan written by André from what you logged",
        "Adjusted every week against your actual progress",
        "Exercises swapped when something hurts or the gym is packed",
        "Nutrition guidance fitted to your goal",
        "Direct chat with your coach, answered the same day",
      ],
    },
  },
};

/**
 * Which tier a paid subscription belongs to.
 *
 * There is no column for this and no way to add one from here, so it is read
 * from what the person pays, which Stripe already syncs into
 * `stripe_subscriptions.amount_cents`.
 *
 * It matches the app price exactly, and treats everything else as coaching,
 * because the first draft used "anything under 99 euros is the app tier" and
 * Francisco pays 50, a price André gave him personally. Under that rule a real
 * coaching client would have started receiving automatic plans and been told
 * on his own dashboard that the app writes them. Reading an unknown amount as
 * coaching fails in the safe direction: the coach stays in charge and nothing
 * is written over his work.
 *
 * Old app prices stay listed here when the price changes, so people who
 * subscribed at the old one keep their tier.
 */
const APP_AMOUNTS_CENTS = new Set<number>([
  3500, // current
  2900, // the launch price, live for a few hours on 2026-09-29
]);

export function tierForAmount(amountCents: number | null | undefined): Tier | null {
  if (typeof amountCents !== "number" || amountCents <= 0) return null;
  return APP_AMOUNTS_CENTS.has(amountCents) ? "app" : "coaching";
}

export function tierAmount(tier: Tier): number {
  return TIERS[tier].amountCents;
}

export function isTier(value: unknown): value is Tier {
  return value === "app" || value === "coaching";
}

/** "35" and "127", for copy that should not carry cents. */
export function priceLabel(tier: Tier): string {
  return String(Math.round(TIERS[tier].amountCents / 100));
}
